DROP SCHEMA IF EXISTS CHAT_PROYECTO; 
CREATE SCHEMA CHAT_PROYECTO;

USE CHAT_PROYECTO; 

DROP TABLE IF EXISTS USUARIO; 

CREATE TABLE USUARIO (
	NOMBRE VARCHAR(35),
    CONTRASEÑA VARCHAR(35),
    USUARIO_ROLE INT NOT NULL, 
    ESTADO BOOLEAN NOT NULL
);

INSERT INTO USUARIO VALUES ('ADMIN','ADMIN',1,TRUE);

DROP PROCEDURE IF EXISTS VALIDATE_USUARIO; 

DELIMITER $$

CREATE PROCEDURE VALIDATE_USUARIO()
BEGIN
	SELECT * FROM USUARIO; 
END $$

DELIMITER ; 

CALL VALIDATE_USUARIO; 

